### ISSUE TITLE
Exception when showing a dummy target

### ISSUE THREAD

**Issue by lawrencetroup** [ensoft/jamjar#1]
jamjar can hit an exception when running 'show' on a dummy target.

It looks like this is related to the target having its timestamp_chain list initialized because 'it is older than' is read in the log; but then no 'inherits timestamp from' line is found, so the list remains empty, and reference to timestamp_chain[-1] raises an exception.

Log (names changed; 'foo' is a dummy target)

(foo) show
name: foo
depends on:
    bar
depended on by:
    baz
includes:
included by:
Traceback (most recent call last):
  File "lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "python/py3-ve/lib/python3.4/site-packages/jamjar/__main__.py", line 36, in <module>
    main(sys.argv[1:])
  File "python/py3-ve/lib/python3.4/site-packages/jamjar/**main**.py", line 31, in main
    cli_ui.cmdloop()
  File "lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "python/py3-ve/lib/python3.4/site-packages/jamjar/ui.py", line 91, in do_targets
    paging_on=self.paging_on).cmdloop()
  File "lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "python/py3-ve/lib/python3.4/site-packages/jamjar/ui.py", line 180, in do_show
    print("timestamp:", self.target.timestamp_chain[-1].timestamp)
IndexError: list index out of range

**Comment by phmc** [comment]
Fixed in PR #2
